### ISSUE TITLE
Icons not showing up at quickmenu

### ISSUE THREAD

**Issue by ONElua** [Ibrahim778/QuickLauncher#1]
Can you make the apps icons be visible in the quickmenu?

![QuickMenuLauncher](https://user-images.githubusercontent.com/25811032/149680239-3cd6c774-c97f-4a93-a856-77bff0d19495.jpg)

Edit
As advice, instead of trying to show the icons from ux0: point the path to ur0:appmeta
The icons at ur0:appmeta are decrypted

**Comment by Ibrahim778** [comment]
Thanks, I really really needed that one.

**Comment by Ibrahim778** [comment]
Should be fixed in V1.2
