### ISSUE TITLE
What happens if you don't create a quicklauncher.txt file?

### ISSUE THREAD

**Issue by ghost** [Ibrahim778/QuickLauncher#3]
My guess would be it would not work but my suggestion is that you could probably add a feature that will function like Trackplugin which you can sort by recently used or most used.

**Comment by Ibrahim778** [comment]
You're right, it wont work
I lack the time to add more features tho, why not try doing it yourself?

**Comment by ghost** [comment]
I mean sure I could do that (if I even know how to do that)

**Comment by ghost** [comment]
I think you have to seperate the plugin or else it won't work.
