### ISSUE TITLE
Clarify where/how to enable the plugin in the README

### ISSUE THREAD

**Issue by Soundtoxin** [Ibrahim778/QuickLauncher#5]
I was thinking with the .suprx extension that this would just go under *main and not *KERNEL but so far I haven't noticed any visual change. Does this have to be above certain other things to work? Is the config file really supposed to be all lowercase? I'm not sure what's wrong here. I tried moving the line to enable it to several spots in the file and rebooted several times.

These are the lines I've been moving around my config.txt
```
# app launcher buttons for quickmenu
ur0:tai/QuickLauncher.suprx
```

This is my quicklauncher.txt contents
```
VITASHELL;PKGJ00000;NPXS10015
```

**Comment by Soundtoxin** [comment]
Do I need your other plugin, QuickMenuReborn, to use QuickLauncher? This was not made clear. I thought it would just modify the system quickmenu.
Do I need a QuickMenuReborn folder? I heard this mentioned in a closed issue, but it's not mentioned in the README as a requirement.

**Comment by Soundtoxin** [comment]
https://github.com/Ibrahim778/QuickMenuReborn/#installing-plugins-that-use-quickmenureborn

Okay, found more clear instructions here. When linked straight to the QuickLauncher repo it's quite confusing to get this going, so I hope to see the README fleshed out more later on.

So for anyone else that comes across this:

1) Install QuickMenuReborn following its README instructions, put it in your tai folder + config.txt under *main
2) You also need to create the QuickMenuReborn folder at ur0: or ux0: and put qmr_plugin.rco inside it
3) QuickLauncher.suprx goes in the same folder as qmr_plugin.rco, NOT your tai folder, does NOT need a line in your config.txt
4) Create quicklauncher.txt at ux0:data/ as described in the README, paying attention to formatting (9 character app titleid separated by a semicolon) and not leaving in any extra spaces, tabs, newlines, etc.
5) Reboot
5) Long press PS button and scroll down, you should see new square icons for the apps you put in quicklauncher.txt

**Comment by Ibrahim778** [comment]
Done
