### ISSUE TITLE
Last app from quicklauncher.txt doesn't show in QuickLauncher

### ISSUE THREAD

**Issue by Soundtoxin** [Ibrahim778/QuickLauncher#6]
My config is the following:
```
VITASHELL;PKGJ00000;NPXS10015
```

The last app is the system Settings app. I found the TitleID here: https://www.psdevwiki.com/vita/index.php?title=Title_ID

It also happens to be in your example line in the README...
```
ABCD12345;BHBB00001;NPXS10015
```
Here is my actual file to soothe any worries you may have about the whitespace.
[quicklauncher.txt](https://github.com/Ibrahim778/QuickLauncher/files/11775938/quicklauncher.txt)

Here's a screenshot (feel free to use it in the README to solve https://github.com/Ibrahim778/QuickLauncher/issues/4 , though I understand if you don't want PKGJ showing)

![2023-06-16-160620](https://github.com/Ibrahim778/QuickLauncher/assets/3146494/58b47882-89f6-432f-a914-a05512eedda1)

As you can see, only the first two of the three apps are showing. I don't know if it's an issue specific to system apps or what.

**Comment by Ibrahim778** [comment]
Your config had an extra newline at the end. Not sure why you didn't see it and I should honestly fix this in the plugin
I'll get round to it later but meanwhile this config should work for you.
[quicklauncher.txt](https://github.com/Ibrahim778/QuickLauncher/files/11778007/quicklauncher.txt)

**Comment by Soundtoxin** [comment]
Huh. My version doesn't have a visible newline in vim, cat, or vitashell. I wouldn't have believed you, except when I run the `file` command on both versions of the file, mine says `ASCII text` and yours says `ASCII text, with no line terminators`. What are you making/editing the file with? You're indeed right that it works with your version of the config, so thanks for that.
I know DOS and UNIX have different line endings, like CRLF vs LF. The last one in a file is probably invisible in most programs by default.

https://stackoverflow.com/questions/3860519/see-line-breaks-and-carriage-returns-in-editor#comment111552028_58190922

I found here that if you give cat the -e argument you can get it to show the line ending, although I'm not exactly sure how I'd remove it if it's invisible in my editor. This seems like a more serious issue to me than I thought it was originally (I thought some people were just not reading the instructions carefully, but now I think it's not their fault).

After some experimenting, it seems like the basic graphical text editor "mousepad" is able to display that invisible newline at the end of a file and delete it. After doing so, I get the same sha1sum from your file and mine post-edit. I have never had to look out for this before that I can remember.

**Comment by Ibrahim778** [comment]
I used notepad++ on windows.

**Comment by Soundtoxin** [comment]
Can you link the commit that fixed this?

**Comment by Ibrahim778** [comment]
I didn't fix it yet

**Comment by Soundtoxin** [comment]
Oh, you closed the issue as if it were solved, though.

**Comment by Ibrahim778** [comment]
This is a caveat I specifically mentioned in the readme
I don't want to push changes to this repo rn because I want to push changes to the QuickMenuReborn repo itself first
